### ISSUE TITLE
Obsolete(?) site still published at http://acrmp.github.io/foodcritic/

### ISSUE THREAD

**Issue by L2G** [acrmp/foodcritic-site#2]
An old version of the Foodcritic site is still available at http://acrmp.github.io/foodcritic/.

This is the top result for Foodcritic on at least one search engine, DuckDuckGo (see https://duckduckgo.com/?q=chef+foodcritic). I've already let them know about it and the new site; hopefully they can make a nice, shiny "Official site" badge in their search results for you.

**Comment by dwradcliffe** [comment]
Even this site seems to be obsolete now?

**Comment by acrmp** [comment]
Thanks Larry. I've made the old `gh-pages` site redirect to the newer foodcritic.io site.

David - I've published changes to the newer site that were pushed but unpublished.

**Comment by dwradcliffe** [comment]
@acrmp Maybe we could get something setup to auto-deploy? Seems to be a few commits behind again.
