### ISSUE TITLE
Add documentation on ignoring rules via inline comments.

### ISSUE THREAD

**Issue by Poohblah** [acrmp/foodcritic-site#21]
Per https://github.com/acrmp/foodcritic/issues/115, individual rule violations can be ignored via inline comments in source code, but this isn't documented anywhere.  It took me a while and some digging through the source code to figure out that the correct way to format the comment is as follows:

    some_code_here # ~FCXXX

Where `XXX` is the number of the rule to ignore.

**Comment by Chucheen** [comment]
+1.
If it wasn't by @Poohblah, it would've taken a the same or even more time as him to figure it out.
