### ISSUE TITLE
Rule examples on homepage, comments decrease readability

### ISSUE THREAD

**Issue by sparr** [acrmp/foodcritic-site#29]
For some of the rules, there are two code blocks adjacent to each other:

```
# Don't do this
Foo
```

and

```
Bar
```

This would be easier to read if the second block also started with a comment line, so the equivalent lines match up horizontally. Maybe just a simple "# Do this instead"?

(FC006 has "# This is ok" solving this problem.)

Originally misfiled as https://github.com/acrmp/foodcritic/issues/416

**Comment by tas50** [comment]
I cleaned up the majority of these and added a few more examples when I was in there. If you see anymore I missed you can just open a PR. The rules are all stored in a big yml file that's parsed into the website.
